// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "2SQmPymfszsnNKcdo8tP3wv9hHYfOFIBrZ2fXLTlvwI8gjQr5bXIXGKaC9V9gsTXqEOsXV";
}
}
}

